package com.example.tmsandroid

const val LAST_MATCH_KEY = "LAST_MATCH_KEY"
const val LAST_MATCH_THUMBNAIL_KEY = "LAST_MATCH_THUMBNAIL_KEY"
const val LAST_MATCH_TITLE_KEY = "LAST_MATCH_TITLE_KEY"
const val LAST_MATCH_COMPETITION_KEY = "LAST_MATCH_COMPETITION_KEY"
const val LAST_MATCH_DATE_KEY = "LAST_MATCH_DATE_KEY"
const val DEFAULT_TEXT = ""
